export const INIT_STUDENTS = "INIT_STUDENTS";
export const GET_NATIONALITIES = "GET_NATIONALITIES";
export const GET_STUDENTS_BY_NATIONALITY = "GET_STUDENTS_BY_NATIONALITY";
export const ADD_NEW_STUDENT = "ADD_NEW_STUDENT";
export const HANDLE_NATIONALITY_SELECT = "HANDLE_NATIONALITY_SELECT";
